<?php
/**
 * Copyright © 2016 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<div class="admin__page-section-title">
    <span class="title"><?php /* @escapeNotVerified */ echo $block->getHeaderText() ?></span>
    <?php if($block->getButtonsHtml()): ?>
        <div class="actions" style="float: right"><?php echo $block->getButtonsHtml() ?></div>
    <?php endif; ?>
</div>
<?php echo $block->getChildHtml('', true) ?>