<?php
/**
 * Copyright © 2016 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<div class="message message-notice">
    <div class="message-inner">
        <div class="message-content">
            <?php echo __('Changing address information will not recalculate tax.') ?>
        </div>
    </div>
</div>

<?php echo $block->getAddressForm(); ?>
<?php echo $block->getSubmitButtonHtml() ?>
<?php echo $block->getCancelButtonHtml() ?>