<?php /** @var \ParadoxLabs\Subscriptions\Block\Customer\Edit $block */ ?>
<?php /* @codingStandardsIgnoreFile */ ?>
<?php $activeCard = $block->getCard(); ?>

<p class="change-notice message warning">
    <?php echo $block->escapeHtml(__('Any changes to the settings below will take effect with the next billing.')); ?>
</p>

<form class="form-subscription-edit form-address-edit" action="<?php echo $block->escapeUrl($block->getSaveUrl()) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php echo $block->escapeQuote(__('* Required Fields')) ?>" data-mage-init='{"subscriptionsEdit":{},"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php echo $block->escapeHtml(__('Payment Information')) ?></span></legend><br>
        <?php echo $block->getBlockHtml('formkey')?>
        <div class="field card required">
            <label class="label" for="tokenbase_id"><span><?php echo $block->escapeHtml(__('Payment Account')) ?></span></label>
            <div class="control">
                <select name="tokenbase_id" id="tokenbase_id" class="validate-select control-select">
                    <?php /** @var \Magento\Vault\Api\Data\PaymentTokenInterface $card */ ?>
                    <?php foreach ($block->getCustomerCards() as $card): ?>
                        <option value="<?php echo $block->escapeQuote($card->getPublicHash()); ?>"<?php if ($card->getPublicHash() == $activeCard->getPublicHash()): ?> selected="selected"<?php endif; ?> title="<?php echo $block->escapeQuote(__('Payment Account')) ?>"><?php echo $block->escapeHtml($block->getCardLabel($card)); ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <?php if (!empty($block->getTokenbaseHelper()->getActiveMethods())): ?>
            <div class="field">
                <p>
                    <?php echo $block->escapeHtml(__('To change your payment options, please go to')); ?>
                    <a href="<?php echo $block->escapeUrl($block->getUrl('customer/paymentinfo')); ?>" target="_blank"><?php echo $block->escapeHtml(__('My Payment Data')); ?></a>.
                </p>
            </div>
        <?php endif; ?>
    </fieldset>
    <?php if ((bool)$block->getSubscription()->getQuote()->getIsVirtual() === false): ?>
        <?php echo $block->getChildHtml('subscriptions_edit_shipping'); ?>
    <?php endif; ?>
    <?php echo $block->getChildHtml('additional'); ?>
    <div class="actions-toolbar widget">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?php echo $block->escapeQuote(__('Save Subscription')) ?>">
                <span><?php echo $block->escapeHtml(__('Save Subscription')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php echo $block->escapeHtml(__('Go back')) ?></span></a>
        </div>
    </div>
</form>
