<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="footer-container">
    <div class="footer-topline">
    	<div class="footer content">
        	<div class="featured_brand">
            	<ul>
                    <li><img src="{{view url="images/webmd_logo.jpg"}}" alt=""></li>
                    <li><img src="{{view url="images/ehow_health_logo.jpg"}}" alt=""></li>
                    <li><img src="{{view url="images/md_junction_logo.jpg"}}" alt=""></li>
                    <li><img src="{{view url="images/drugs_com_logo.jpg"}}" alt=""></li>
                </ul>
            </div>
            <div class="block newsletter">
            	dsfdsfs
            </div>
        </div>
    </div>
    <div class="footer content">
        <div class="block newsletter">sdfds</div>
        <ul class="footer links">
        	<li><a href="#">dsfdsfd</a></li>
            <li><a href="#">dsfdsfd</a></li>
            <li><a href="#">dsfdsfd</a></li>
            <li><a href="#">dsfdsfd</a></li>
        </ul>
    </div>
    <div class="footer-bottomline">
    	<div class="footer content">
        	<ul>
            	<li><img src="{{view url="images/inspire_commerce_logo.jpg"}}" alt=""></li>
                <li><img src="{{view url="images/godaddy_secure_logo.jpg"}}" alt=""></li>
                <li><img src="{{view url="images/operation_smile_logo.jpg"}}" alt=""></li>
                <li><img src="{{view url="images/operation_smile_logo.jpg"}}" alt=""></li>
                <li><img src="{{view url="images/operation_smile_logo.jpg"}}" alt=""></li>
                <li><img src="{{view url="images/made_usa_logo.jpg"}}" alt=""></li>
            </ul>
        </div>
    </div>
</div>