<div class="about_intro">
    <div class="wrapper">
        <div class="content clearfix">
            <div class="ytube_video">
             <!--<img src='<?php //echo $this->getViewFileUrl('images/youtube_video.jpg'); ?>' alt="" /> -->
            <iframe width="300" height="169" src="https://www.youtube.com/embed/4j693oR9-yk?list=PLLoz4IwahnPZBlRoNtny8Rh_J1vCJ82Pa" frameborder="0" allowfullscreen></iframe>
            </div>
            <div class="intro_img"><img src='<?php echo $this->getViewFileUrl('images/emuaid-canhelp.png'); ?>' alt="" /></div>
            <div class="money_back_guarantee"><img src='<?php echo $this->getViewFileUrl('images/30days-badge.png'); ?>' alt="" />
            	<p>We are so confident in the healing powers of EMUAID that we gurantee you&rsquo;ll experience less inlammation, less itching and less pain within the first 24 hours of use. However, if you are in any way dissatisfied with our product or its results we&rsquo;ll fully refund your intial purchase within 30 days</p>
            </div>
        </div>
    </div>
</div>



