
   
    <div class="footer-middle clearfix">
        <div class="footer content">
        	<div class="foot_row clearfix">
            	<div class="foot_logo"><a href="#"><img src='<?php echo $this->getViewFileUrl('images/logo_footer.png'); ?>' alt=""></a></div>	
                <div class="foot_other_links">
                	<ul>
                    	<li><span class="live_help"><strong>Live Help</strong> Online</span></li>
                        <li><span class="free_ship">Free <strong>Shipping</strong></span></li>
                        <li><span class="call"><tel>1-800-881-3900</tel>Toll Free</span></li>
                        <li>
                        	<div class="social_media">
                                <a class="fb_ico" href="www.facebook.com/emuaid">Facebook</a>
                                <a class="twt_ico" href="#">Twitter</a>
                                <a class="gplus_ico" href="#">GPlus</a>
                                <a class="ytube_ico" href="#">Youtube</a>  
                                <a class="linkedin_ico" href="#">LinkedIn</a>                    
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="foot_row last clearfix">
            	<div class="links">
                    <ul>
                        <li><a href="#">Our Founder </a></li> 
                        <li><a href="<?php echo $this->getBaseUrl()?>FAQ">FAQ  </a></li>
                        <li><a href="<?php echo $this->getBaseUrl()?>ingredient-glossary">Ingredient Glossary </a></li>
                        <li><a href="#">Cutsomer Reviews </a></li>  
                        <li><a href="<?php echo $this->getBaseUrl()?>contact">Contact us  </a></li>
                        <li><a href="<?php echo $this->getBaseUrl()?>terms-conditions">Terms &amp; Conditions</a></li>
                    </ul>	
                    <p class="copyright"> 
					<?php echo $this->getLayout()->createBlock("Magento\Theme\Block\Html\Footer")->setTemplate("Magento_Theme::html/copyright.phtml")->toHtml();?>| Speer Laboratories, 5821 N. Andrews Way, Ft Lauderdale, FL 33309</p>
                </div>
                <span class="pym_card"><img src='<?php echo $this->getViewFileUrl('images/cc-icon.png'); ?>' alt=""></span>	
            </div>
                        
        </div>
    </div>
    <div class="footer-bottomline">
    	<div class="footer content">
        	<ul>
            	<li><img src='<?php echo $this->getViewFileUrl('images/inspire_commerce_logo.jpg'); ?>' alt=""></li>
                <li><img src='<?php echo $this->getViewFileUrl('images/godaddy_secure_logo.jpg'); ?>' alt=""></li>
                <li><img src='<?php echo $this->getViewFileUrl('images/operation_smile_logo.jpg'); ?>' alt=""></li>
                <li><a href="http://www.shopperapproved.com/certificates/emuaid.com/" onclick="var nonwin=navigator.appName!='Microsoft Internet Explorer'?'yes':'no'; var certheight=screen.availHeight-90; window.open(this.href,'shopperapproved','location='+nonwin+',scrollbars=yes,width=620,height='+certheight+',menubar=no,toolbar=no'); return false;">
					<img src="https://c813008.ssl.cf2.rackcdn.com/6675-small.jpg" alt="" oncontextmenu="var d = new Date(); alert('Copying Prohibited by Law - This image and all included logos are copyrighted by shopperapproved \251 '+d.getFullYear()+'.'); return false;"></a></li>
                <li><a href="http://www.bbb.org/south-east-florida/business-reviews/homeopathic-remedies/speer-laboratories-in-pompano-beach-fl-90038501#sealclick" title="Click for the Business Review of Speer Laboratories, LLC, a Homeopaths in Pompano Beach FL" target="_blank">
					<img alt="Click for the BBB Business Review of this Homeopaths in Pompano Beach FL" src="https://seal-Seflorida.bbb.org/seals/black-seal-96-50-speerlaboratoriesllc-90038501.png" style="opacity: 1;"></a></li>
				<li><img src='<?php echo $this->getViewFileUrl('images/made_usa_logo.jpg'); ?>' alt=""></li>
            </ul>
        </div>
    </div>