<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
$image = 'cart_cross_sell_products';
?>
<script type="text/javascript" src="https://www.shopperapproved.com/thankyou/sv-draw_js.php?site=6675"></script><script src="https://www.shopperapproved.com/thankyou/opt-in.js" type="text/javascript"></script>
<script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>
<div id="fb-root"></div>
    <script>
        // <![CDATA[
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
        // ]]>
    </script>

<?php if ($this->getOrderId()): ?>
    <div class="ordershare">
        <h2><?php echo $block->escapeHtml(__('Why not share your purchase to twitter or facebook?')) ?></h2>
        <?php $order = $this->getOrder(); ?>
        <?php $items = $order->getItemsCollection() ?>

        <div class="block-content content">
            <div class="products wrapper grid products-grid products">
                <ol class="products list items product-items">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php if ($_item->getParentItem()) {
                            continue;
                        } ?>
                        <?php $_product = $_item->getProduct();?>
                        <?php $twitterText = $block->escapeHtml(__("I just bought a '".$_product->getName()."' from Emuaid")); ?>
                        <?php $twitterUser = $this->getTwitterUser(); ?>
						<li class="item product product-item">
                        <div class="product-item-info">
                            <?php /* @escapeNotVerified */
                            echo '<!-- ' . $image . '-->' ?>
                            <a href="<?php /* @escapeNotVerified */
                            echo $this->getProductUrl($_product) ?>" class="product photo product-item-photo">
                                <?php echo $this->getImage($_product, $image)->toHtml(); ?>
                            </a>
                            <div class="product details product-item-details">
                                <strong class="product name product-item-name"><a class="product-item-link"
                                                                                  title="<?php echo $this->escapeHtml($_product->getName()) ?>"
                                                                                  href="<?php /* @escapeNotVerified */
                                                                                  echo $this->getProductUrl($_product) ?>">
                                        <?php echo $this->escapeHtml($_product->getName()) ?></a>
                                </strong>
                                <?php $twitterUser = $this->getTwitterUser();?>
                                <div class="share">
                                    <div class="twitter">
                                        <a href="http://twitter.com/share" class="twitter-share-button"
                                           data-url="<?php echo $this->getProductUrl($_product) ?>"
                                           data-text="<?php echo $twitterText ?>"
                                           data-count="vertical">Tweet</a>
                                    </div>
                                    <div class="fb-share-button" data-href="<?php echo $this->getProductUrl($_product) ?>" data-layout="button" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="<?php echo $this->getFacebookUrl($_product);?>">Share</a></div>
                                </div>
                            </div>
                        </div>
                        <?php echo ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>
<?php endif; ?>

