<?php
/**
 * @author Amit Samsukha <amit@emizentech.com>
 */
?>
<?php
$stores  = $this->getAllStores();
?>
<?php foreach($stores as $_store):?>
		<?php //var_dump($_store->debug());?>
		<?php $lt = $_store->getLatitude();?>
		<?php $lg = $_store->getLongitude();?>
<?php endforeach;?>

    
    
	<!--<script src="http://maps.google.com/maps/api/js" ></script> -->
	<script src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyCN-7nICN4HM6Vkb1filOtaFAJmOLIhTUI"></script>
    <script>
    var map;
    var markers = [];
    var infoWindow;
    var locations;

    function init() {
      map = new google.maps.Map(document.getElementById("map"), {
        center: new google.maps.LatLng(<?php echo $lt?>, <?php echo $lg?>),
        zoom: 10,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
         mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU}
      });
      infoWindow = new google.maps.InfoWindow();

      locations = document.getElementById("locations");
   }

   function searchLocations() {
     var address = document.getElementById("addressInput").value;
     var geocoder = new google.maps.Geocoder();
     geocoder.geocode({address: address}, function(results, status) {
       if (status == google.maps.GeocoderStatus.OK) {
        searchLocationsNear(results[0].geometry.location);
       } else {
         alert(address + ' not found');
       }
     });
   }

   function clearLocations() {
     infoWindow.close();
     for (var i = 0; i < markers.length; i++) {
       markers[i].setMap(null);
     }
     markers.length = 0;

     locations.innerHTML = "";
   }
   
   function searchLocationsNear(center) {
     clearLocations();

     var radius = document.getElementById('radiusSelect').value;
     var searchUrl = '<?php echo $this->getUrl('storelocator/index/search');?>?lat=' + center.lat() + '&lng=' + center.lng() + '&radius=' + radius;
     downloadUrl(searchUrl, function(data) {
       var xml = parseXml(data);
       var markerNodes = xml.documentElement.getElementsByTagName("marker");
       var bounds = new google.maps.LatLngBounds();

        var source = document.getElementById("addressInput").value;

     if (source) {
         for (var i = 0; i < markerNodes.length; i++) {
             var name = markerNodes[i].getAttribute("name");
             var address = markerNodes[i].getAttribute("address");
             var distance = parseFloat(markerNodes[i].getAttribute("distance"));
             var latlng = new google.maps.LatLng(
                 parseFloat(markerNodes[i].getAttribute("lat")),
                 parseFloat(markerNodes[i].getAttribute("lng")));

             createOption(name, address, distance, source);
             createMarker(latlng, name, address);
             bounds.extend(latlng);
         }
     }

       map.fitBounds(bounds);
       locations.style.visibility = "visible";
      });
    }
  
    function createMarker(latlng, name, address) {
      var html = "<b>" + name + "</b> <br/>" + address;
      var marker = new google.maps.Marker({
        map: map,
        position: latlng
      });
      google.maps.event.addListener(marker, 'click', function() {
        infoWindow.setContent(html);
        infoWindow.open(map, marker);
      });
      markers.push(marker);
    }

    function createOption(name, address, distance, source) {
        var newNode = document.createElement('div');
		newNode.classList.add("str_row");
        html = "<div class='str_name'><span>"+name+"</span><span>"+distance.toFixed(1)+" miles</span></div>";
        html += "<div class='str_address'>"+ address +"</div>";
        html += "<div class='str_direction'>"+"<a href='http://maps.google.com/maps?saddr="+encodeURI(source)+"&amp;daddr="+encodeURI(address)+"' target='_blank' class='storelocatorlink'>Directions</a>"+"</div>";
        newNode.innerHTML = html;
        locations.appendChild(newNode);
    }

    function downloadUrl(url, callback) {
      var request = window.ActiveXObject ?
          new ActiveXObject('Microsoft.XMLHTTP') :
          new XMLHttpRequest;

      request.onreadystatechange = function() {
        if (request.readyState == 4) {
          request.onreadystatechange = doNothing;
          callback(request.responseText, request.status);
        }
      };

      request.open('GET', url, true);
      request.send(null);
    }

    function parseXml(str) {
      if (window.ActiveXObject) {
        var doc = new ActiveXObject('Microsoft.XMLDOM');
        doc.loadXML(str);
        return doc;
      } else if (window.DOMParser) {
        return (new DOMParser).parseFromString(str, 'text/xml');
      }
    }
	
	function doNothing(){}
	
	google.maps.event.addDomListener(window, 'load', init);

  </script>
  <div class="store_srch">
    <div class="field">
    <div class="control">
	<label>Address / Zip</label>
     <input type="text" class="input-text" id="addressInput" />
	 <label>Within</label>
		<select id="radiusSelect" class="input-select">
			<option value="" >Select Distance</option>
			<option value="10">10 miles</option>
		  	<option value="25" >25 miles</option>
			<option value="50">50 miles</option>
		  	<option value="100">100 miles</option>
		  	<option value="200" selected>200 miles</option>
			<option value="500">500 miles</option>
		</select>
    	<button type="submit" onclick="searchLocations()" class="submit primary button">Find Locations</button>
    </div>
    </div>
    </div>
    <div style="clear:both;"></div>
    <div id="map" class="store-map" style="width: 100%; height: 80%"></div>

<div id="locations" style="width:100%;visibility:hidden">

</div>
